return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    -- Bootstrap installation of parsers (no-op if already installed).
    -- Synchronous wait so parsers are ready on first startup.
    require('nvim-treesitter').install {
      'bash',
      'c',
      'cmake',
      'comment',
      'cpp',
      'css',
      'diff',
      'dockerfile',
      'go',
      'html',
      'java',
      'javascript',
      'json',
      'json5',
      'lua',
      'make',
      'markdown',
      'markdown_inline',
      'python',
      'query',
      'regex',
      'sql',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
    }:wait(600000)
  end,
}